In [2]:
import torch
#1D Tensor
x = torch.tensor([2,2,1])
print(x)

tensor([2, 2, 1])


In [14]:
#2D Tensor
y = torch.FloatTensor([[1,2,3],[4,5,6],[7,8,9]])
print(y)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [18]:
#Size of Tensor
print(x.size())
print(y.dtype)

torch.Size([3])
torch.float32


In [21]:
#Reshaping
print(y.view(-1,1))
print(y.view(9))

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])


In [23]:
r = torch.randn(3,3)
print(r)

tensor([[-1.1096, -0.0454,  0.5640],
        [-0.6899,  0.4739, -0.8153],
        [-0.1139, -0.2411, -1.8464]])


In [29]:
#Converting numpy into torch tensor
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,2,out =a)
print(a)
print(b)

[3. 3. 3. 3. 3.]
tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [30]:
cuda = torch.cuda.is_available()
print(cuda)

False
